### ISSUE TITLE
parser in src_file() fails if files end with comments

### ISSUE THREAD

**Issue by GregorDeCillia** [strboul/supreme#4]
Hello,

I just tried your package with one of my apps and found out that `*.R` files that end in comments are not handled correctly in `src_file()`. Take the following app as an example.

```r
mod_test <- function(input, output, session) {}

library(shiny)

shinyApp(
    ui = fluidPage(),
    server = function(input, output) {
        callModule(mod_test, "some_id")
    }
)

# comment
```

Using this app in `src_file()` leads to an error

```r
supreme::src_file("app.R")
#> Error in parse(text = lines) : <text>:13:0: unexpected end of input
#> 11: 
#> 12: # comment }
```

My guess is that there is a mismatched curly brace because a closing brace is added to the same line as the comment. If I add two newlines after `# comment`, the app is parsed correctly.

**Comment by strboul** [comment]
Hi Gregor,

Thanks for filling this issue and providing a good test case. And sorry for the late reply, somehow I didn't get any notification for this issue when it's created.

Your guess is correct! I fixed the problem you described, but I'd still recommend you structure the source code a little bit different. To make supreme work: 1) the ui and server parts must be written as functions/objects 2) all server-side modules (including the server itself) must have `input, output, session` arguments.

This is mainly because supreme does static analysis on the code and it's not very easy to cover every case. I described this behavior in the "Current limitations"  section of the README file (see [here](https://github.com/strboul/supreme/blob/f62266408aac5170989f10605935c1aae429e55b/README.md#current-limitations)). You may be missed that as that part is still in progress.

For example, your code in the `app.R` file can be rewritten in a way like below and therefore supreme will be able to read it better:

```r
mod_test <- function(input, output, session) {}

library(shiny)

ui <- fluidPage()

server <- function(input, output, session) {
  callModule(mod_test, "some_id")
}

shinyApp(ui, server)

# comment
```
