### ISSUE TITLE
Error in ret[["data"]][[1L]] : subscript out of bounds

### ISSUE THREAD

**Issue by sk-sahu** [strboul/supreme#9]
Trying to create the object from a file path 

```R
app_path <- "/home/user/Documents/0_git/app_name/R/app.R"
obj <- supreme(src_file(app_path))
```
In the same directory, I have the modules in different R files.

Error:
```
Error in ret[["data"]][[1L]] : subscript out of bounds
```

**Comment by strboul** [comment]
That looks like a bug. However, it's impossible to say anything without seeing the underlying code. Would it be possible for you to share the `app.R` or something similar to it (if you cannot share the source code)?

Please note that if your app is in the directory, then you'll need to tell all the paths to supreme. Anyway, that error message isn't helpful so it should be improved.

**Comment by sk-sahu** [comment]
I'm trying on this project - https://github.com/sk-sahu/sig-bio-shiny/

Although my `app.R` present in `inst/app`, I have tried to move it to `R` directory where all the modules are present. 

I tried to provide all the paths as given with example object from `example_app_path()` but the error was consistent.

**Comment by strboul** [comment]
Ah, I can see know why it failed. *supreme* couldn't find the initial `server` because the `session` argument was missing in the `server()`. This behavior is mentioned under the [Known Limitations](https://github.com/strboul/supreme#known-limitations) section. 

I see this graph when I add the `session` argument to the `server()` in the `app.R`:

![Screenshot 2020-06-11 at 18 49 13](https://user-images.githubusercontent.com/25015317/84416596-b8531f00-ac14-11ea-95ac-6b2bb742af23.png)

I'll patch the package as I think it's better to have some meaningful error message for these kinds of behaviors.
